import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import AppBar from "./components/AppBar";
import PageContainer from "./components/common/PageContainer";
import StyledStack from "./components/common/PageStyledStack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppBar />
          <main>
            <PageContainer>
              <StyledStack>{children}</StyledStack>
            </PageContainer>
          </main>
        </Providers>
      </body>
    </html>
  );
}
