"""add an enum for the therapist type

Revision ID: 0ce6b49629fb
Revises: f55d8af6a9c3
Create Date: 2026-01-22 22:31:08.748950+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0ce6b49629fb"
down_revision: Union[str, Sequence[str], None] = "f55d8af6a9c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    therapist_type_enum = sa.Enum(
        "PSYCHOLOGIST",
        "PSYCHOTHERAPIST",
        "SOCIAL_WORKER",
        "REGISTERED_PRACTITIONER",
        name="therapisttypeoption",
    )
    therapist_type_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "therapists",
        "therapist_type",
        existing_type=sa.VARCHAR(),
        type_=therapist_type_enum,
        postgresql_using="therapist_type::therapisttypeoption",
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "therapists",
        "therapist_type",
        existing_type=sa.Enum(
            "PSYCHOLOGIST",
            "PSYCHOTHERAPIST",
            "SOCIAL_WORKER",
            "REGISTERED_PRACTITIONER",
            name="therapisttypeoption",
        ),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
