"""test score patient therapist change

Revision ID: 2449d84445d9
Revises: 2e5e67461dd1
Create Date: 2025-09-03 18:38:05.207071+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2449d84445d9"
down_revision: Union[str, Sequence[str], None] = "2e5e67461dd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("patients_personality_test_id_fkey"), "patients", type_="foreignkey"
    )
    op.drop_column("patients", "personality_test_id")
    op.add_column(
        "personality_test_scores", sa.Column("patient_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "personality_test_scores",
        sa.Column("therapist_id", sa.Integer(), nullable=True),
    )
    op.create_unique_constraint(None, "personality_test_scores", ["therapist_id"])
    op.create_unique_constraint(None, "personality_test_scores", ["patient_id"])
    op.create_foreign_key(
        None, "personality_test_scores", "therapists", ["therapist_id"], ["id"]
    )
    op.create_foreign_key(
        None, "personality_test_scores", "patients", ["patient_id"], ["id"]
    )
    op.drop_constraint(
        op.f("therapists_personality_test_id_fkey"), "therapists", type_="foreignkey"
    )
    op.drop_column("therapists", "personality_test_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "therapists",
        sa.Column(
            "personality_test_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("therapists_personality_test_id_fkey"),
        "therapists",
        "personality_test_scores",
        ["personality_test_id"],
        ["id"],
    )
    op.drop_constraint(None, "personality_test_scores", type_="foreignkey")
    op.drop_constraint(None, "personality_test_scores", type_="foreignkey")
    op.drop_constraint(None, "personality_test_scores", type_="unique")
    op.drop_constraint(None, "personality_test_scores", type_="unique")
    op.drop_column("personality_test_scores", "therapist_id")
    op.drop_column("personality_test_scores", "patient_id")
    op.add_column(
        "patients",
        sa.Column(
            "personality_test_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("patients_personality_test_id_fkey"),
        "patients",
        "personality_test_scores",
        ["personality_test_id"],
        ["id"],
    )
    # ### end Alembic commands ###
