"""Update Therapist Patient Models

Revision ID: 2e5e67461dd1
Revises: 04325c177403
Create Date: 2025-09-01 21:33:35.157794+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2e5e67461dd1"
down_revision: Union[str, Sequence[str], None] = "04325c177403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients",
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "patients",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "description")
    op.drop_column("patients", "location")
    # ### end Alembic commands ###
