"""initial_schema

Revision ID: 33e1db5d22d1
Revises:
Create Date: 2026-01-12 20:34:46.850212+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "33e1db5d22d1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_patients",
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("therapy_needs", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_lgbtq_therapist_preference", sa.Boolean(), nullable=True),
        sa.Column("is_religious_therapist_preference", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anonymous_patients_session_id"),
        "anonymous_patients",
        ["session_id"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "anonymous_personality_test_scores",
        sa.Column(
            "neuroticism", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("openness", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "extroversion", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "conscientiousness", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "agreeableness", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("anonymous_patient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anonymous_patient_id"], ["anonymous_patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anonymous_patient_id"),
    )
    op.create_table(
        "patients",
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("therapy_needs", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_lgbtq_therapist_preference", sa.Boolean(), nullable=True),
        sa.Column("is_religious_therapist_preference", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "therapists",
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("therapist_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("specializations", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("therapist_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["therapists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personality_test_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("neuroticism", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("openness", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("extroversion", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column(
            "conscientiousness", sa.Numeric(precision=5, scale=3), nullable=False
        ),
        sa.Column("agreeableness", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("therapist_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["therapist_id"], ["therapists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_id"),
        sa.UniqueConstraint("therapist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personality_test_scores")
    op.drop_table("matches")
    op.drop_table("therapists")
    op.drop_table("patients")
    op.drop_table("anonymous_personality_test_scores")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_anonymous_patients_session_id"), table_name="anonymous_patients"
    )
    op.drop_table("anonymous_patients")
    # ### end Alembic commands ###
