"""add latitude + longitude coordinates for user

Revision ID: 456032f57c32
Revises: 6fecce6d8fbf
Create Date: 2025-10-14 23:40:18.340033+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "456032f57c32"
down_revision: Union[str, Sequence[str], None] = "6fecce6d8fbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anonymous_patients", sa.Column("latitude", sa.Float(), nullable=True)
    )
    op.add_column(
        "anonymous_patients", sa.Column("longitude", sa.Float(), nullable=True)
    )
    op.drop_column("anonymous_patients", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anonymous_patients",
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("anonymous_patients", "longitude")
    op.drop_column("anonymous_patients", "latitude")
    # ### end Alembic commands ###
