"""add postal code to anonymous sessions table

Revision ID: 48dfc9608b32
Revises: 6dfe3bdcf05c
Create Date: 2025-11-17 20:19:04.487920+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "48dfc9608b32"
down_revision: Union[str, Sequence[str], None] = "6dfe3bdcf05c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anonymous_patients",
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anonymous_patients", "postal_code")
    # ### end Alembic commands ###
