"""add is_profile_complete field to therapist

Revision ID: 601c7bfb1941
Revises: fa9053416c6b
Create Date: 2026-03-02 18:33:21.159853+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "601c7bfb1941"
down_revision: Union[str, Sequence[str], None] = "fa9053416c6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "therapists",
        sa.Column(
            "is_profile_complete",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("therapists", "is_profile_complete")
    # ### end Alembic commands ###
