"""add religious + lgbtq therapist preference to patient model

Revision ID: 6dfe3bdcf05c
Revises: 456032f57c32
Create Date: 2025-10-23 14:43:13.194347+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6dfe3bdcf05c"
down_revision: Union[str, Sequence[str], None] = "456032f57c32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anonymous_patients",
        sa.Column("is_lgbtq_therapist_preference", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "anonymous_patients",
        sa.Column("is_religious_therapist_preference", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "patients",
        sa.Column("is_lgbtq_therapist_preference", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "patients",
        sa.Column("is_religious_therapist_preference", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "is_religious_therapist_preference")
    op.drop_column("patients", "is_lgbtq_therapist_preference")
    op.drop_column("anonymous_patients", "is_religious_therapist_preference")
    op.drop_column("anonymous_patients", "is_lgbtq_therapist_preference")
    # ### end Alembic commands ###
