"""add anonymous session + score tables

Revision ID: 6fecce6d8fbf
Revises: f311e0bf4876
Create Date: 2025-10-02 14:02:52.419326+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fecce6d8fbf"
down_revision: Union[str, Sequence[str], None] = "f311e0bf4876"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_patients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("therapy_needs", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "gender",
            postgresql.ENUM(
                "MALE",
                "FEMALE",
                "NON_BINARY",
                "PREFER_NOT_TO_SAY",
                "OTHER",
                name="genderoption",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anonymous_patients_session_id"),
        "anonymous_patients",
        ["session_id"],
        unique=True,
    )
    op.create_table(
        "anonymous_personality_test_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("neuroticism", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("openness", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("extroversion", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column(
            "conscientiousness", sa.Numeric(precision=5, scale=3), nullable=False
        ),
        sa.Column("agreeableness", sa.Numeric(precision=5, scale=3), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["anonymous_patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anonymous_personality_test_scores")
    op.drop_index(
        op.f("ix_anonymous_patients_session_id"), table_name="anonymous_patients"
    )
    op.drop_table("anonymous_patients")
    # ### end Alembic commands ###
