"""add cascade delete to the therapists model

Revision ID: 725caa9a2cbb
Revises: facc3476c486
Create Date: 2026-03-11 20:29:39.874935+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "725caa9a2cbb"
down_revision: Union[str, Sequence[str], None] = "facc3476c486"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("patients_user_id_fkey"), "patients", type_="foreignkey")
    op.create_foreign_key(
        None, "patients", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("therapists_user_id_fkey"), "therapists", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "therapists", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "therapists", type_="foreignkey")
    op.create_foreign_key(
        op.f("therapists_user_id_fkey"), "therapists", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "patients", type_="foreignkey")
    op.create_foreign_key(
        op.f("patients_user_id_fkey"), "patients", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
