"""edit anonymous_patient personality test score fields and unique fields

Revision ID: 792da156a99e
Revises: 48dfc9608b32
Create Date: 2025-11-28 23:41:31.652234+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "792da156a99e"
down_revision: Union[str, Sequence[str], None] = "48dfc9608b32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anonymous_personality_test_scores",
        sa.Column("anonymous_patient_id", sa.Uuid(), nullable=False),
    )
    op.create_unique_constraint(
        None, "anonymous_personality_test_scores", ["anonymous_patient_id"]
    )
    op.create_foreign_key(
        None,
        "anonymous_personality_test_scores",
        "anonymous_patients",
        ["anonymous_patient_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "anonymous_personality_test_scores", type_="foreignkey")
    op.drop_constraint(None, "anonymous_personality_test_scores", type_="unique")
    op.drop_column("anonymous_personality_test_scores", "anonymous_patient_id")
    # ### end Alembic commands ###
