"""Fix Tables for Users with Auth

Revision ID: 7efcb14f9500
Revises: 0a842ef43b41
Create Date: 2025-08-29 19:38:21.269877+00:00

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[import]
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7efcb14f9500"
down_revision: Union[str, Sequence[str], None] = "0a842ef43b41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("patients", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "patients", "users", ["user_id"], ["id"])
    op.drop_column("patients", "first_name")
    op.drop_column("patients", "description")
    op.drop_column("patients", "email_address")
    op.drop_column("patients", "location")
    op.drop_column("patients", "last_name")
    op.add_column("therapists", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "therapists", "users", ["user_id"], ["id"])
    op.drop_column("therapists", "email_address")
    op.drop_column("therapists", "first_name")
    op.drop_column("therapists", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "therapists",
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "therapists",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "therapists",
        sa.Column("email_address", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "therapists", type_="foreignkey")
    op.drop_column("therapists", "user_id")
    op.add_column(
        "patients",
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "patients",
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "patients",
        sa.Column("email_address", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "patients",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "patients",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "patients", type_="foreignkey")
    op.drop_column("patients", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
