"""update anonymous personality test table for category enum

Revision ID: 8958d3318246
Revises: 792da156a99e
Create Date: 2025-12-18 20:22:17.180180+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8958d3318246"
down_revision: Union[str, Sequence[str], None] = "792da156a99e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_personality_test_scores",
        sa.Column(
            "neuroticism", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("openness", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "extroversion", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "conscientiousness", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "agreeableness", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("anonymous_patient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anonymous_patient_id"], ["anonymous_patients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("anonymous_patient_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anonymous_personality_test_scores")
    # ### end Alembic commands ###
