"""update the user model to add a roles column

Revision ID: 9500f512767d
Revises: 0ce6b49629fb
Create Date: 2026-01-27 16:58:29.877053+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9500f512767d"
down_revision: Union[str, Sequence[str], None] = "0ce6b49629fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("roles", postgresql.ARRAY(sa.String()), nullable=True)
    )
    op.drop_column("users", "user_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_type",
            postgresql.ENUM("PATIENT", "THERAPIST", name="useroption"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
