"""restore_manually_dropped_table

Revision ID: bfb7b946a019
Revises: 8958d3318246
Create Date: 2026-01-06 00:14:54.121014+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bfb7b946a019"
down_revision: Union[str, Sequence[str], None] = "8958d3318246"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=True),
        sa.Column("therapist_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["therapists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "anonymous_patients", sa.Column("latitude", sa.Float(), nullable=True)
    )
    op.add_column(
        "anonymous_patients", sa.Column("longitude", sa.Float(), nullable=True)
    )
    op.add_column(
        "anonymous_patients",
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "anonymous_patients",
        sa.Column("is_lgbtq_therapist_preference", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "anonymous_patients",
        sa.Column("is_religious_therapist_preference", sa.Boolean(), nullable=True),
    )
    op.drop_column("anonymous_patients", "location")
    op.add_column(
        "anonymous_personality_test_scores",
        sa.Column("anonymous_patient_id", sa.Uuid(), nullable=False),
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "neuroticism",
        existing_type=sa.NUMERIC(precision=5, scale=3),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="to_json(neuroticism)",
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "openness",
        existing_type=sa.NUMERIC(precision=5, scale=3),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="to_json(openness)",
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "extroversion",
        existing_type=sa.NUMERIC(precision=5, scale=3),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="to_json(extroversion)",
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "conscientiousness",
        existing_type=sa.NUMERIC(precision=5, scale=3),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="to_json(conscientiousness)",
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "agreeableness",
        existing_type=sa.NUMERIC(precision=5, scale=3),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="to_json(agreeableness)",
    )
    op.drop_constraint(
        op.f("anonymous_personality_test_scores_patient_id_key"),
        "anonymous_personality_test_scores",
        type_="unique",
    )
    op.create_unique_constraint(
        None, "anonymous_personality_test_scores", ["anonymous_patient_id"]
    )
    op.drop_constraint(
        op.f("anonymous_personality_test_scores_patient_id_fkey"),
        "anonymous_personality_test_scores",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "anonymous_personality_test_scores",
        "anonymous_patients",
        ["anonymous_patient_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("anonymous_personality_test_scores", "patient_id")
    op.create_foreign_key(None, "patients", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "therapists", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "therapists", type_="foreignkey")
    op.drop_constraint(None, "patients", type_="foreignkey")
    op.add_column(
        "anonymous_personality_test_scores",
        sa.Column("patient_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "anonymous_personality_test_scores", type_="foreignkey")
    op.create_foreign_key(
        op.f("anonymous_personality_test_scores_patient_id_fkey"),
        "anonymous_personality_test_scores",
        "anonymous_patients",
        ["patient_id"],
        ["id"],
    )
    op.drop_constraint(None, "anonymous_personality_test_scores", type_="unique")
    op.create_unique_constraint(
        op.f("anonymous_personality_test_scores_patient_id_key"),
        "anonymous_personality_test_scores",
        ["patient_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "agreeableness",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.NUMERIC(precision=5, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "conscientiousness",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.NUMERIC(precision=5, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "extroversion",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.NUMERIC(precision=5, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "openness",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.NUMERIC(precision=5, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "anonymous_personality_test_scores",
        "neuroticism",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.NUMERIC(precision=5, scale=3),
        existing_nullable=False,
    )
    op.drop_column("anonymous_personality_test_scores", "anonymous_patient_id")
    op.add_column(
        "anonymous_patients",
        sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("anonymous_patients", "is_religious_therapist_preference")
    op.drop_column("anonymous_patients", "is_lgbtq_therapist_preference")
    op.drop_column("anonymous_patients", "postal_code")
    op.drop_column("anonymous_patients", "longitude")
    op.drop_column("anonymous_patients", "latitude")
    op.drop_table("matches")
    op.drop_table("users")
    # ### end Alembic commands ###
