"""add type to the user model

Revision ID: f55d8af6a9c3
Revises: 33e1db5d22d1
Create Date: 2026-01-22 16:41:39.680602+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f55d8af6a9c3"
down_revision: Union[str, Sequence[str], None] = "33e1db5d22d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    useroption_enum = sa.Enum("PATIENT", "THERAPIST", name="useroption")
    useroption_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "anonymous_patients",
        "gender",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "MALE",
            "FEMALE",
            "NON_BINARY",
            "PREFER_NOT_TO_SAY",
            "OTHER",
            name="genderoption",
        ),
        postgresql_using="gender::genderoption",
        existing_nullable=True,
    )
    op.alter_column(
        "patients",
        "gender",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "MALE",
            "FEMALE",
            "NON_BINARY",
            "PREFER_NOT_TO_SAY",
            "OTHER",
            name="genderoption",
        ),
        postgresql_using="gender::genderoption",
        existing_nullable=True,
    )
    op.alter_column(
        "therapists",
        "gender",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "MALE",
            "FEMALE",
            "NON_BINARY",
            "PREFER_NOT_TO_SAY",
            "OTHER",
            name="genderoption",
        ),
        postgresql_using="gender::genderoption",
        existing_nullable=True,
    )
    op.add_column(
        "users",
        sa.Column(
            "user_type",
            sa.Enum("PATIENT", "THERAPIST", name="useroption"),
            nullable=True,
        ),
    )
    op.drop_column("users", "is_anonymous")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_anonymous", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "user_type")
    op.alter_column(
        "therapists",
        "gender",
        existing_type=sa.Enum(
            "MALE",
            "FEMALE",
            "NON_BINARY",
            "PREFER_NOT_TO_SAY",
            "OTHER",
            name="genderoption",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "patients",
        "gender",
        existing_type=sa.Enum(
            "MALE",
            "FEMALE",
            "NON_BINARY",
            "PREFER_NOT_TO_SAY",
            "OTHER",
            name="genderoption",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "anonymous_patients",
        "gender",
        existing_type=sa.Enum(
            "MALE",
            "FEMALE",
            "NON_BINARY",
            "PREFER_NOT_TO_SAY",
            "OTHER",
            name="genderoption",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
