"""add gender and age columns

Revision ID: f812c23f4253
Revises: 5a7af67e5b75
Create Date: 2025-09-23 19:33:05.379480+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f812c23f4253"
down_revision: Union[str, Sequence[str], None] = "5a7af67e5b75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    gender_option_enum = postgresql.ENUM(
        "MALE",
        "FEMALE",
        "NON_BINARY",
        "PREFER_NOT_TO_SAY",
        "OTHER",
        name="genderoption",
    )
    gender_option_enum.create(op.get_bind())

    op.add_column("patients", sa.Column("age", sa.Integer(), nullable=False))
    op.add_column(
        "patients",
        sa.Column(
            "gender",
            sa.Enum(
                "MALE",
                "FEMALE",
                "NON_BINARY",
                "PREFER_NOT_TO_SAY",
                "OTHER",
                name="genderoption",
            ),
            nullable=False,
        ),
    )
    op.add_column("therapists", sa.Column("age", sa.Integer(), nullable=False))
    op.add_column(
        "therapists",
        sa.Column(
            "gender",
            sa.Enum(
                "MALE",
                "FEMALE",
                "NON_BINARY",
                "PREFER_NOT_TO_SAY",
                "OTHER",
                name="genderoption",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("therapists", "gender")
    op.drop_column("therapists", "age")
    op.drop_column("patients", "gender")
    op.drop_column("patients", "age")

    gender_option_enum = postgresql.ENUM(
        "MALE",
        "FEMALE",
        "NON_BINARY",
        "PREFER_NOT_TO_SAY",
        "OTHER",
        name="genderoption",
    )
    gender_option_enum.drop(op.get_bind())
    # ### end Alembic commands ###
