"""add the aggregate therapist test data table

Revision ID: fa9053416c6b
Revises: 9500f512767d
Create Date: 2026-02-17 21:01:33.917153+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa9053416c6b"
down_revision: Union[str, Sequence[str], None] = "9500f512767d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "therapist_personality_tests",
        sa.Column(
            "neuroticism", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("openness", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "extroversion", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "conscientiousness", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "agreeableness", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("therapist_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["therapist_id"], ["therapists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("therapist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("therapist_personality_tests")
    # ### end Alembic commands ###
