"""add lgbtq + religious specialization to the user model

Revision ID: facc3476c486
Revises: fb353f31518c
Create Date: 2026-03-06 16:14:30.695910+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "facc3476c486"
down_revision: Union[str, Sequence[str], None] = "fb353f31518c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "therapists", sa.Column("is_lgbtq_specialization", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "therapists",
        sa.Column("is_religious_specialization", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("therapists", "is_religious_specialization")
    op.drop_column("therapists", "is_lgbtq_specialization")
    # ### end Alembic commands ###
