"""add postal_code to therapist model

Revision ID: fb353f31518c
Revises: 601c7bfb1941
Create Date: 2026-03-05 21:15:46.523796+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fb353f31518c"
down_revision: Union[str, Sequence[str], None] = "601c7bfb1941"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "patients",
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "therapists",
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("therapists", "postal_code")
    op.drop_column("patients", "postal_code")
    # ### end Alembic commands ###
